/*
 * var.cpp
 *
 *  Created on: 16 de jul de 2024
 *      Author: COELMATIC2022
 */

#include "gui/global/var.hpp"

int tickCountCycle25					= 0;
int tickCountCapture					= 0;
int tickCountPortaAberta				= 0;

bool flag_Inicilizar_APLICACAO			= false;

double SP_SONDA_CONGELAR_CAMARA			= 0;
double Diferencial_Congelar_tempo		= 0;
double Timer_Congelar_DECORRIDO_SP 		= 0;
double Timer_Congelar_DECORRIDO_ON 		= 0;
bool flag_Processo_ANDAMENTO			= false;
bool Timer_delay_ON						= false;
bool flag_alarm_receita_vazia			= true;
double Status_tecla_Congela				= 0;
bool Timer_Congelar_DECORRIDO_OUT		= false;
bool flag_Conservar_S_N					= false;
bool flag_transicao_Conservar			= false;
bool flag_Conservar_Cong_Resf			= false;
bool Timer_buzzer_ON 					= false;
double Timer_delay_OUT 					= 0;
double SP_SONDA_RESF_CAMARA				= 0;
double SP_Resfriar_Sonda				= 0;
double SP_Resfriar_Tempo_SOFT			= 0;
double Diferencial_Resfriar_Tempo		= 0;
double SP_Resf_Hard_Interno_display		= 0;
double SP_Resf_Hard_Espeto_display		= 0;
double SP_Resf_Interno_F1				= 0;
double SP_Resf_Interno_F2				= 0;
double SP_Resf_Espeto_F1				= 0;
double SP_Resf_Espeto_F2				= 0;
double Hard_Resf_fase_numero			= 0;
double Dif_Resf_Hard_F1					= 0;
double Dif_Resf_Hard_F2					= 0;
double Timer_SP_MINUTOS_Resfriar		= 0;
double Preset_Resf_Tempo_F1				= 0;
double Preset_Resf_Tempo_F2				= 0;
double Porc_Resf_preset_tempo_F1F2		= 0;
bool xBeep_once							= false;
bool flag_Resfriar_HARD_SOFT			= false;
double W_HSW9 							= 0;
double Timer_buzzer_SP 					= 0;
double W_HAW8000 						= 0;
double Timer_COUNT_MINUTOS 				= 0;
double Timer_Delay_SP 					= 0;
double Timer_Degelo_SP 					= 0;
double Timer_degelo_delay_SP 			= 0;
double numero_receita					= 0;
double initial_value					= 0;
double Timer_SP_MINUTOS					= 0;
double SP_Conservar_Congelar			= 0;
double Diferencial_Conservar_COngelar	= 5;
double SP_Conservar_Resfriar			= 0;
double Diferencial_Conservar_Resfriar	= 0;
double CONGELAR_SONDA_SP				= 0;
double SP_Congelar_Tempo				= 0;
double SP_Resfriar_Tempo_HARD			= 0;
double logica_entrada_digital1			= 1;
double logica_entrada_digital2			= 0;
double timer_alarme_externo_SP_MINUTOS	= 0;
double Timer_Alarme_externo_SP			= 0;
double flag_hab_desab_Tecla_REDIAL		= 0;
double Senha_Gravada					= 123;
bool degelo_porta_aberta				= false;
bool degelo_processo_automatico			= false;
double Timer_Congelar_DECORRIDO_COUNT	= 0;
double Timer_Degelo_COUNT_MINUTOS		= 0;
double Timer_degelo_COUNT				= 0;
double Timer_higiene_MIN				= 0;
double Timer_higiene_COUNT				= 0;
double flag_alarme_externo_andamento	= 0;
double flag_alarme_externo				= 0;
double Timer_alarme_externo_ON			= 0;
double Tempo_estimado_Congelar_SONDA 	= 0;
double Tempo_estimado_Resfriar_Sonda 	= 0;
double Tempo_Estimado_Receita_Temperat	= 0;
double Timer_Buzzer_COUNT				= 0;
bool Timer_BUzzer_OUT					= false;
bool Timer_buzzer_DEG_ON				= false;
double Timer_Buzzer_DEG_COUNT			= 0;
bool Timer_BUzzer_DEG_OUT				= false;
double Timer_Delay_COUNT				= 0;
double Timer_degelo_delay_ON			= 0;
double Timer_degelo_delay_COUNT			= 0;
bool Timer_degelo_delay_OUT				= false;
double Timer_Degelo_CONTROL				= 0;
double Timer_Alarme_externo_COUNT		= 0;
double timer_higiene_ON					= 0;
bool Timer_Degelo_OUT					= false;
bool Timer_alarme_externo_OUT			= false;
bool timer_higiene_OUT					= false;
bool HSW4								= false;
bool reset_fabrica						= false;
bool cancelar_processo_SIM				= false;
double xbar_zero						= 0;
bool flag_Conservar_ANDAMENTO			= false;
double Status_Conservar					= 0;
bool Receita_Cong_Resf_ATUAL			= false;
double Status_Porta						= 0;
bool flag_porta							= false;
double Temperatura_Receita_ATUAL		= 0;
bool flag_cancelar_degelo_SIM			= false;
bool flag_degelo_andamento				= false;
bool Status_degelo						= false;
double Timer_Degelo_ON					= 0;
double delay_comp						= 0;
bool flag_congelar_SONDA				= false;
bool flag_resfriar_Sonda_tempo			= false;
bool flag_START_RECEITA					= false;
double Tempo_Receita_ATUAL				= 0;
bool Receita_Hard_Soft_ATUAL			= false;
bool flag_congelar_Tempo                = false;
bool flag_inicio_degelo					= false;
bool flag_edit_receita					= false;
bool flag_Receita1_interm				= false;
bool flag_Receita2_interm				= false;
bool flag_Receita3_interm				= false;
bool Receita_Conserv_ATUAL				= false;
bool Receita_time_temp_ATUAL			= false;
bool R1_cong_resf						= false;
bool R2_cong_resf						= false;
bool R3_cong_resf						= false;
bool R4_cong_resf						= false;
bool R5_cong_resf						= false;
bool R6_cong_resf						= false;
bool R7_cong_resf						= false;
bool R8_cong_resf						= false;
bool R9_cong_resf						= false;
bool R10_cong_resf						= false;
bool R11_cong_resf						= false;
bool R12_cong_resf						= false;
bool R1_Hard_Soft						= false;
bool R2_Hard_Soft						= false;
bool R3_Hard_Soft						= false;
bool R4_Hard_Soft						= false;
bool R5_Hard_Soft						= false;
bool R6_Hard_Soft						= false;
bool R7_Hard_Soft						= false;
bool R8_Hard_Soft						= false;
bool R9_Hard_Soft						= false;
bool R10_Hard_Soft						= false;
bool R11_Hard_Soft						= false;
bool R12_Hard_Soft						= false;
bool R1_Conserv_yn						= false;
bool R2_Conserv_yn						= false;
bool R3_Conserv_yn						= false;
bool R4_Conserv_yn						= false;
bool R5_Conserv_yn						= false;
bool R6_Conserv_yn						= false;
bool R7_Conserv_yn						= false;
bool R8_Conserv_yn						= false;
bool R9_Conserv_yn						= false;
bool R10_Conserv_yn						= false;
bool R11_Conserv_yn						= false;
bool R12_Conserv_yn						= false;
bool R1_time_temp						= false;
bool R2_time_temp						= false;
bool R3_time_temp						= false;
bool R4_time_temp						= false;
bool R5_time_temp						= false;
bool R6_time_temp						= false;
bool R7_time_temp						= false;
bool R8_time_temp						= false;
bool R9_time_temp						= false;
bool R10_time_temp						= false;
bool R11_time_temp						= false;
bool R12_time_temp						= false;
double Tempo_receita_1					= 0;
double Tempo_receita_2					= 0;
double Tempo_receita_3					= 0;
double Tempo_receita_4					= 0;
double Tempo_receita_5					= 0;
double Tempo_receita_6					= 0;
double Tempo_receita_7					= 0;
double Tempo_receita_8					= 0;
double Tempo_receita_9					= 0;
double Tempo_receita_10					= 0;
double Tempo_receita_11					= 0;
double Tempo_receita_12					= 0;
double Temperatura_receita_01			= 0;
double Temperatura_receita_02			= 0;
double Temperatura_receita_03			= 0;
double Temperatura_receita_04			= 0;
double Temperatura_receita_05			= 0;
double Temperatura_receita_06			= 0;
double Temperatura_receita_07			= 0;
double Temperatura_receita_08			= 0;
double Temperatura_receita_09			= 0;
double Temperatura_receita_10			= 0;
double Temperatura_receita_11			= 0;
double Temperatura_receita_12			= 0;
char Receita_1_desc[20];
char Receita_2_desc[20];
char Receita_3_desc[20];
char Receita_4_desc[20];
char Receita_5_desc[20];
char Receita_6_desc[20];
char Receita_7_desc[20];
char Receita_8_desc[20];
char Receita_9_desc[20];
char Receita_10_desc[20];
char Receita_11_desc[20];
char Receita_12_desc[20];
char W_HAW8214[20];
char W_HAW8235[20];
bool flag_redefine_senha				= false;
double Estado_Redial_Receita			= 0;
double Senha_usuario					= 0;
bool Confere_senha						= false;
bool status_higiene						= false;
bool start_higiene						= false;
bool cancela_higiene					= false;
double W_HDW5000_ANT					= 0;
double W_HDW5000						= 0;

double W_1_4512							= 0;
double W_1_4515							= 0;
double W_1_4518							= 0;
double W_1_4553							= 0;
double W_1_4554							= 0;
double W_1_4555							= 0;
double W_1_4556							= 0;
double W_1_4645							= 0;
double W_1_4625							= 0;
double W_1_4513							= 0;
double W_1_4641							= 0;
double W_1_4324							= 0;
double W_1_4640							= 0;
double W_1_410272						= 0;
double W_1_410275						= 0;
double W_1_410299						= 0;
double W_1_410242						= 0;
double W_1_410282						= 0;
double W_1_410270						= 0;
double W_1_410291						= 0;
double W_1_410248						= 0;
double W_1_410249						= 0;
double W_1_410250						= 0;
double W_1_410323						= 0;
double W_1_410322						= 0;
double W_1_410294						= 0;
double W_1_410256						= 0;
double W_1_410258						= 0;
double W_1_410255						= 0;
double W_1_410279						= 0;
double W_1_410295						= 0;
double W_1_410324						= 0;

double W1410242							= 0;

bool flag_recuperar_leitura_dig			= false;
bool flag_recuperar_leitura_begin		= false;
