################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJDUMP_LIST := 
C_UPPER_DEPS := 
S_DEPS := 
C_DEPS := 
CC_DEPS := 
OBJCOPY_HEX := 
SIZE_OUTPUT := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
S_UPPER_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ADDITIONAL/GFX \
ADDITIONAL/GFX/Module/Src \
APPLICAZIONE/Components/FatFs \
APPLICAZIONE/Components/Modbus/Client \
APPLICAZIONE/Components/Modbus/INT \
APPLICAZIONE/Components/Modbus/RS485 \
APPLICAZIONE/Components/Modbus/Serial \
APPLICAZIONE/Components/Modbus/Server \
APPLICAZIONE/Components/Modbus/TCPIP \
APPLICAZIONE/Components/Modbus/TTL \
APPLICAZIONE/Components/Modbus \
APPLICAZIONE/Components/TouchDrivers/Resistive \
APPLICAZIONE/Components/TouchDrivers/gt911 \
APPLICAZIONE/Components/TouchDrivers/hycon \
APPLICAZIONE/Components/TouchDrivers \
APPLICAZIONE/Drivers/STM32F7xx_HAL_Driver/Src \
APPLICAZIONE/GFX \
APPLICAZIONE/GFX/Module/Src \
APPLICAZIONE/Libraries/FatFs/App \
APPLICAZIONE/Libraries/FatFs/Target \
APPLICAZIONE/Libraries/FatFs/src \
APPLICAZIONE/Libraries/FatFs/src/option \
APPLICAZIONE/Libraries/LwIP \
APPLICAZIONE/Libraries/QSPI \
APPLICAZIONE/Libraries/USB/STM32_USB_Device_Library/Class/CDC/Src \
APPLICAZIONE/Libraries/USB/STM32_USB_Device_Library/Core/Src \
APPLICAZIONE/Libraries/USB/STM32_USB_Host_Library/Class/MSC/Src \
APPLICAZIONE/Libraries/USB/STM32_USB_Host_Library/Core/Src \
APPLICAZIONE/Libraries/USB \
APPLICAZIONE/Modules/Brightness \
APPLICAZIONE/Modules/Buzzer \
APPLICAZIONE/Modules/Converter \
APPLICAZIONE/Modules/Display \
APPLICAZIONE/Modules/FatFs \
APPLICAZIONE/Modules/Job \
APPLICAZIONE/Modules/Language \
APPLICAZIONE/Modules/Manager \
APPLICAZIONE/Modules/Math \
APPLICAZIONE/Modules/Memory \
APPLICAZIONE/Modules/Modbus \
APPLICAZIONE/Modules/Settings \
APPLICAZIONE/Modules/TS \
APPLICAZIONE/Modules/Time \
APPLICAZIONE/Peripherals/Src \
APPLICAZIONE/TestBench/TTLTest \
APPLICAZIONE/TestBench/TestBench \
APPLICAZIONE/TestBench/UsbModbus \
APPLICAZIONE/Utils \
Core/Src \
Middlewares/Third_Party/LwIP/src/api \
Middlewares/Third_Party/LwIP/src/apps/mqtt \
Middlewares/Third_Party/LwIP/src/core \
Middlewares/Third_Party/LwIP/src/core/ipv4 \
Middlewares/Third_Party/LwIP/src/core/ipv6 \
Middlewares/Third_Party/LwIP/src/netif \
Middlewares/Third_Party/LwIP/src/netif/ppp \
Middlewares/Third_Party/LwIP/system/OS \
OS/Source/CMSIS_RTOS \
OS/Source \
OS/Source/portable/GCC/ARM_CM7/r0p1 \
OS/Source/portable/MemMang \
STARTUP \
TouchGFX/App \
TouchGFX/build/Px4/Core/Src \
TouchGFX/build/Px4/Middlewares/Third_Party/LwIP/src/api \
TouchGFX/build/Px4/Middlewares/Third_Party/LwIP/src/apps/mqtt \
TouchGFX/build/Px4/Middlewares/Third_Party/LwIP/src/core \
TouchGFX/build/Px4/Middlewares/Third_Party/LwIP/src/core/ipv4 \
TouchGFX/build/Px4/Middlewares/Third_Party/LwIP/src/core/ipv6 \
TouchGFX/build/Px4/Middlewares/Third_Party/LwIP/src/netif \
TouchGFX/build/Px4/Middlewares/Third_Party/LwIP/src/netif/ppp \
TouchGFX/build/Px4/Middlewares/Third_Party/LwIP/system/OS \
TouchGFX/build/Px4/TouchGFX/App \
TouchGFX/build/Px4/TouchGFX/generated/fonts/src \
TouchGFX/build/Px4/TouchGFX/generated/gui_generated/src/common \
TouchGFX/build/Px4/TouchGFX/generated/gui_generated/src/containers \
TouchGFX/build/Px4/TouchGFX/generated/gui_generated/src/splashscreen_screen \
TouchGFX/build/Px4/TouchGFX/generated/gui_generated/src/testscreen_screen \
TouchGFX/build/Px4/TouchGFX/generated/images/src \
TouchGFX/build/Px4/TouchGFX/generated/images/src/__designer \
TouchGFX/build/Px4/TouchGFX/generated/texts/src \
TouchGFX/build/Px4/TouchGFX/gui/src/common \
TouchGFX/build/Px4/TouchGFX/gui/src/containers \
TouchGFX/build/Px4/TouchGFX/gui/src/model \
TouchGFX/build/Px4/TouchGFX/gui/src/splashscreen_screen \
TouchGFX/build/Px4/TouchGFX/gui/src/testscreen_screen \
TouchGFX/build/Px4/TouchGFX/target \
TouchGFX/build/Px4/TouchGFX/target/generated \
TouchGFX/build/Px4/gcc/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 \
TouchGFX/build/Px4/gcc/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
TouchGFX/build/bin \
TouchGFX/generated/fonts/src \
TouchGFX/generated/gui_generated/src/alarme_externo_screen \
TouchGFX/generated/gui_generated/src/common \
TouchGFX/generated/gui_generated/src/configuracao_2_screen \
TouchGFX/generated/gui_generated/src/configuracao_3_screen \
TouchGFX/generated/gui_generated/src/configuracao_4_screen \
TouchGFX/generated/gui_generated/src/configuracao_5_screen \
TouchGFX/generated/gui_generated/src/configuracao_6_screen \
TouchGFX/generated/gui_generated/src/configuracao_7_screen \
TouchGFX/generated/gui_generated/src/configuracao_screen \
TouchGFX/generated/gui_generated/src/congelar_screen \
TouchGFX/generated/gui_generated/src/congelar_select_tempo_screen \
TouchGFX/generated/gui_generated/src/congelar_sonda_screen \
TouchGFX/generated/gui_generated/src/congelar_tempo_screen \
TouchGFX/generated/gui_generated/src/conservacao_screen \
TouchGFX/generated/gui_generated/src/conservar_congelar_screen \
TouchGFX/generated/gui_generated/src/conservar_resfriar_screen \
TouchGFX/generated/gui_generated/src/containers \
TouchGFX/generated/gui_generated/src/degelo_confirmar_screen \
TouchGFX/generated/gui_generated/src/degelo_screen \
TouchGFX/generated/gui_generated/src/inicializacao_screen \
TouchGFX/generated/gui_generated/src/receita_confirm_screen \
TouchGFX/generated/gui_generated/src/receitas_1_edit_screen \
TouchGFX/generated/gui_generated/src/receitas_1_screen \
TouchGFX/generated/gui_generated/src/receitas_2_screen \
TouchGFX/generated/gui_generated/src/receitas_3_screen \
TouchGFX/generated/gui_generated/src/refine_senha_secreto_screen \
TouchGFX/generated/gui_generated/src/reset_fabrica_screen \
TouchGFX/generated/gui_generated/src/resfriar_screen \
TouchGFX/generated/gui_generated/src/resfriar_select_tempo_screen \
TouchGFX/generated/gui_generated/src/resfriar_sonda_screen \
TouchGFX/generated/gui_generated/src/resfriar_tempo_screen \
TouchGFX/generated/gui_generated/src/tela_inicial_screen \
TouchGFX/generated/images/src \
TouchGFX/generated/images/src/__designer \
TouchGFX/generated/texts/src \
TouchGFX/gui/src/alarme_externo_screen \
TouchGFX/gui/src/background \
TouchGFX/gui/src/common \
TouchGFX/gui/src/configuracao_2_screen \
TouchGFX/gui/src/configuracao_3_screen \
TouchGFX/gui/src/configuracao_4_screen \
TouchGFX/gui/src/configuracao_5_screen \
TouchGFX/gui/src/configuracao_6_screen \
TouchGFX/gui/src/configuracao_7_screen \
TouchGFX/gui/src/configuracao_screen \
TouchGFX/gui/src/congelar_screen \
TouchGFX/gui/src/congelar_select_tempo_screen \
TouchGFX/gui/src/congelar_sonda_screen \
TouchGFX/gui/src/congelar_tempo_screen \
TouchGFX/gui/src/conservacao_screen \
TouchGFX/gui/src/conservar_congelar_screen \
TouchGFX/gui/src/conservar_resfriar_screen \
TouchGFX/gui/src/containers \
TouchGFX/gui/src/degelo_confirmar_screen \
TouchGFX/gui/src/degelo_screen \
TouchGFX/gui/src/inicializacao_screen \
TouchGFX/gui/src/model \
TouchGFX/gui/src/receita_confirm_screen \
TouchGFX/gui/src/receitas_1_edit_screen \
TouchGFX/gui/src/receitas_1_screen \
TouchGFX/gui/src/receitas_2_screen \
TouchGFX/gui/src/receitas_3_screen \
TouchGFX/gui/src/refine_senha_secreto_screen \
TouchGFX/gui/src/reset_fabrica_screen \
TouchGFX/gui/src/resfriar_screen \
TouchGFX/gui/src/resfriar_select_tempo_screen \
TouchGFX/gui/src/resfriar_sonda_screen \
TouchGFX/gui/src/resfriar_tempo_screen \
TouchGFX/gui/src/tela_inicial_screen \
TouchGFX/target \
TouchGFX/target/generated \

